/** ----------------------------------------
 *              ITEM DATABASE             --
 -----------------------------------------*/
/*Item Types
------------
1. ship
2. cursor
3. galaxy
------------*/

/** --------------------CHANGING--------------------*/
let arrShips = [
  {
    id: 1,
    name: "Rust Bucket",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship-RustBucket.png",
    desc: "I'm not really sure how this ship is flying. It's held together with duct tape and glue.",
    rarity: "common",
    cost: 0,
    owned: "owned",
    equipped: "equipped",
    hidden: "",
    defaultTag: true
  },
  {
    id: 2,
    name: "Novice Ship",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship-NoviceShip.png",
    desc: "This ship is... okay. Better than the Rust Bucket.",
    rarity: "common",
    cost: 1000,
    owned: "",
    equipped: "",
    hidden: "",
    defaultTag: true
  },
  {
    id: 3,
    name: "Traveler's Ship",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship-TravelersShip.png",
    desc: "Now THIS is a ship designed for intergalactic travel. It even has heated seats and cupholders.",
    rarity: "common",
    cost: 3000,
    owned: "",
    equipped: "",
    hidden: "",
    defaultTag: true
  },
  {
    id: 4,
    name: "Space Pirate Vessel",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "Nobody will mess with me while flying this ship around the universe.",
    rarity: "common",
    cost: 10000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 5,
    name: "Alien Space Craft",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "I'm not sure how to fly this thing but I'm certainly going to try.",
    rarity: "rare",
    cost: 30000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 6,
    name: "Pure Gold",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "A space ship made of pure gold. I've got more money than I need and I'm gonna flaunt it!",
    rarity: "rare",
    cost: 100000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 7,
    name: "Flying Crystal",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "One of the most unique and rare ships you'll ever see across the cosmos. A flying chunk of space crystal.",
    cost: 500000,
    rarity: "unique",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 8,
    name: "Overgrown Ship",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "This ship looks like it was grown from something natrual. It's beautiful.",
    cost: 500000,
    rarity: "unique",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 9,
    name: "The Creature",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "This isn't even a ship, but a living creature. Hopefully it doesn't eat me.",
    cost: 500000,
    rarity: "unique",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 10,
    name: "Vintage Shuttle",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "An old vintage space shuttle from my home planet. It's in excellent condition.",
    cost: 500000,
    rarity: "unique",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 11,
    name: "Space Racer",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "I've never flown a faster ship than this. Traveling to new space systems will be near instantaneous with these high tech warp drives.",
    cost: 500000,
    rarity: "unique",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 12,
    name: "The Destroyer",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "This is one of the largest ships I've ever seen. Not only is it intimidating, it's loaded with enough space canons to destroy anything I come across.",
    cost: 500000,
    rarity: "unique",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  },
  {
    id: 13,
    name: "Champions Gauntlet",
    type: "ship",
    img: "../Galaclixy_v3/assets/imgs/ships/Ship1.png",
    desc: "Well, I've done it. I've got it all and explored all corners of the universe, but my journey doesn't have to end here.",
    cost: 1000000,
    rarity: "mythic",
    owned: "",
    equipped: "",
    hidden: "hidden",
    defaultTag: true
  }
];

let arrCursors = [
  {
    id: 1,
    name: "Default Web Browser",
    cssKey: "default",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Default.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Default.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Default.png",
    rarity: "common",
    cost: 0,
    owned: "owned",
    equipped: "equipped",
    hidden: "",
    bonusClicks: 0,
    defaultTag: true
  },
  {
    id: 2,
    name: "Dot",
    cssKey: "dot",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "common",
    cost: 0,
    owned: "owned",
    equipped: "",
    hidden: "",
    bonusClicks: 0,
    defaultTag: true
  },
  {
    id: 3,
    name: "Dot with Lines",
    cssKey: "dot2",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-DotLines-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-DotLines.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-DotLines.png",
    rarity: "common",
    cost: 500,
    owned: "",
    equipped: "",
    hidden: "",
    bonusClicks: 1,
    defaultTag: true
  },
  {
    id: 4,
    name: "Target",
    cssKey: "target",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Target-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Target.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Target.png",
    rarity: "common",
    cost: 800,
    owned: "",
    equipped: "",
    hidden: "",
    bonusClicks: 1,
    defaultTag: true
  },
  {
    id: 5,
    name: "Advanced Target",
    cssKey: "target2",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-AdvancedTarget-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-AdvancedTarget.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-AdvancedTarget.png",
    rarity: "common",
    cost: 2000,
    owned: "",
    equipped: "",
    hidden: "",
    bonusClicks: 2,
    defaultTag: true
  },
  {
    id: 6,
    name: "Superior Target",
    cssKey: "target3",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-SuperiorTarget-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-SuperiorTarget.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-SuperiorTarget.png",
    rarity: "common",
    cost: 3000,
    owned: "",
    equipped: "",
    hidden: "",
    bonusClicks: 2,
    defaultTag: true
  },
  {
    id: 7,
    name: "Arrow",
    cssKey: "arrow",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Arrow-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Arrow.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Arrow.png",
    rarity: "common",
    cost: 3000,
    owned: "",
    equipped: "",
    hidden: "",
    bonusClicks: 2,
    defaultTag: true
  },
  {
    id: 8,
    name: "Cross",
    cssKey: "cross",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Cross-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Cross.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Cross.png",
    rarity: "common",
    cost: 5000,
    owned: "",
    equipped: "",
    hidden: "",
    bonusClicks: 2,
    defaultTag: true
  },
  {
    id: 9,
    name: "Flower",
    cssKey: "flower",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Flower-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Flower.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Flower.png",
    rarity: "rare",
    cost: 10000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 3,
    defaultTag: true
  },
  {
    id: 10,
    name: "Skull",
    cssKey: "skull",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Skull-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Skull.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Skull.png",
    rarity: "rare",
    cost: 10000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 3,
    defaultTag: true
  },
  {
    id: 11,
    name: "Smiley",
    cssKey: "smile",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "rare",
    cost: 10000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 3,
    defaultTag: true
  },
  {
    id: 12,
    name: "Star",
    cssKey: "star",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "rare",
    cost: 10000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 3,
    defaultTag: true
  },
  {
    id: 13,
    name: "Money",
    cssKey: "money",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "rare",
    cost: 50000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 3,
    defaultTag: true
  },
  {
    id: 14,
    name: "Boom",
    cssKey: "boom",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "rare",
    cost: 50000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 3,
    defaultTag: true
  },
  {
    id: 15,
    name: "Asteroid",
    cssKey: "aster",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "unique",
    cost: 100000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 4,
    defaultTag: true
  },
  {
    id: 16,
    name: "Rocket Ship",
    cssKey: "rocket",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "unique",
    cost: 100000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 4,
    defaultTag: true
  },
  {
    id: 17,
    name: "Black Hole",
    cssKey: "blackhole",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "unique",
    cost: 100000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 4,
    defaultTag: true
  },
  {
    id: 18,
    name: "Galaxy",
    cssKey: "gal",
    type: "cursor",
    img: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot-thumb.png",
    cursorImg: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    cursorImgFire: "../Galaclixy_v3/assets/imgs/cursors/Cursor-Dot.png",
    rarity: "mythic",
    cost: 500000,
    owned: "",
    equipped: "",
    hidden: "hidden",
    bonusClicks: 5,
    defaultTag: true
  }
];

let arrGalaxies = [
  {
    id: 1,
    name: "Home Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "This is my Home Galaxy. Where my journey begins.",
    rarity: "common",
    cost: 0,
    hidden: "",
    owned: "owned",
    equipped: "equipped",
    galaxyKey: "G1",
    defaultTag: true
  },
  {
    id: 2,
    name: "Green Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "This Galaxy is filled with a noxious green gas. I'll be safe in my ship.",
    rarity: "common",
    cost: 10000,
    hidden: "",
    owned: "",
    equipped: "",
    galaxyKey: "G2",
    defaultTag: true
  },
  {
    id: 3,
    name: "Blue Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "My radars are picking up extreme cold temperatures from the Blue Galaxy. Better bundle up.",
    rarity: "common",
    cost: 50000,
    hidden: "",
    owned: "",
    equipped: "",
    galaxyKey: "G3",
    defaultTag: true
  },
  {
    id: 4,
    name: "Red Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "There's a lot of radio chatter about pirates in this galaxy.",
    rarity: "rare",
    cost: 100000,
    hidden: "hidden",
    owned: "",
    equipped: "",
    galaxyKey: "G4",
    defaultTag: true
  },
  {
    id: 5,
    name: "Wasteland Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "This galaxy is full of crystalized planets and space rocks.",
    rarity: "rare",
    cost: 250000,
    hidden: "hidden",
    owned: "",
    equipped: "",
    galaxyKey: "G5",
    defaultTag: true
  },
  {
    id: 6,
    name: "Overgrown Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "The planets in this system seem to be full of life and wildly overgrown.",
    rarity: "unique",
    cost: 250000,
    hidden: "hidden",
    owned: "",
    equipped: "",
    galaxyKey: "G6",
    defaultTag: true
  },
  {
    id: 7,
    name: "Cutie Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "There's a pink mist all throughout this galaxy, and the planets are filled with a tiny alien species.",
    rarity: "unique",
    cost: 500000,
    hidden: "hidden",
    owned: "",
    equipped: "",
    galaxyKey: "G7",
    defaultTag: true
  },
  {
    id: 8,
    name: "A super far Galaxy",
    type: "galaxy",
    img: "../Galaclixy_v3/assets/imgs/galaxies/Galaxy-Temp.png",
    desc: "This galaxy is at the edge of known space. Who knows what I'll find out here.",
    rarity: "mythic",
    cost: 1500000,
    hidden: "hidden",
    owned: "",
    equipped: "",
    galaxyKey: "G8",
    defaultTag: true
  }
];

